import { StyleSheet } from "react-native";
import Colors from "./Colors";

export const DefaultStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#FDEFDE",
        paddingHorizontal: 20,
    },
    inputField: {
        height: 50,
        borderRadius: 6,
        borderColor: '#ABABAB',
        borderWidth: 1,
        padding: 12,
        marginVertical: 8,
        backgroundColor: "#FFF",
        fontSize: 16,
    },
    inputFieldFocused: {
        borderColor: Colors.primary,
    },
    btn: {
        backgroundColor: Colors.primary,
        height: 50,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        marginVertical: 12,
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
        elevation: 2,
    },
    btnText: {
        color: '#FFF',
        fontSize: 18,
        fontFamily: 'NunitoBold',
        textAlign: 'center',
        paddingHorizontal: 10
    },
    btnIcon: {
        position: 'absolute',
        left: 16,
    },
    footer: {
        position: 'absolute',
        height: 100,
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#FFF',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderTopColor: Colors.grey,
        borderTopWidth: StyleSheet.hairlineWidth,
        shadowColor: "#000",
        shadowOpacity: 0.05,
        shadowOffset: { width: 0, height: -2 },
        shadowRadius: 4,
        elevation: 1,
    },
    header: {
        height: 60,
        backgroundColor: Colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
        elevation: 2,
    },
    headerText: {
        fontSize: 20,
        fontFamily: 'NunitoBold',
        color: Colors.black,
    },
    card: {
        backgroundColor: '#FFF',
        borderRadius: 12,
        padding: 16,
        marginVertical: 8,
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
        elevation: 2,
        alignItems: 'center',
    },
    cardTitle: {
        fontSize: 18,
        fontFamily: 'NunitoBold',
        marginBottom: 8,
        color: Colors.black,
    },
    cardSubtitle: {
        fontSize: 14,
        fontFamily: 'NunitoLight',
        color: Colors.grey,
    },
});
